# Generated by Django 3.1.5 on 2021-01-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210126_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('type', models.IntegerField(choices=[(4, 'Comedy'), (3, 'Drama'), (2, 'Horror'), (1, 'Sci-fi'), (0, 'Unknown'), (5, 'Document')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='additional_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additional_info'),
        ),
    ]
