# Generated by Django 3.1.5 on 2021-01-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210126_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Sci-fi'), (2, 'Horror'), (3, 'Drama'), (4, 'Comedy'), (5, 'Document')], default=0),
        ),
    ]
